language: python
install:
  - pip install tox
  - pip install coveralls
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=pypy
script:
  - tox -e $TOX_ENV
  - coverage run --source=hangman setup.py test
after_success:
  coveralls